/**
 * Generate routes from data
 *
 * Uses a .json file as base to generate routes for nuxt
 * !This JSON file needs to have a certain structure!
 *
 * Special behaviour for home slugs:
 * We use `/` for the default lang home slug, `/en/` for the english home etc.
 *
 * ⚠️ For now we cannot have nested pages within home `/home/my-nested-slug`
 * 🤷‍ Makes sense to be aware of that!
 *
 * @param {Object} options - The options object to pass in
 * @param {string} options.data
 * @param {Array} [options.section] – the craft sections that should be the source for our routes
 * @param {string} [options.homeSlug]
 * @param {string} [options.debug]
 * @return {Array} An array of routes to be generated by nuxt generate
 *
 */

/* eslint-disable no-console */

import _cloneDeep from 'lodash.clonedeep'
import {
  removeTrailingSlash,
  verifyLeadingSlash
} from '@wearelucid/vuecid-helpers'

import flattenNavigation from '../navigation/flattenNavigation'
import addLanguagePrefixes from '../navigation/addLanguagePrefixes'
import stripTrailingHomeSlug from '../url/stripTrailingHomeSlug'

function generateRoutesFromData(
  options = {
    data: {},
    sections: ['pages'],
    homeSlug: 'home',
    defaultLanguage: 'de',
    debug: false
  }
) {
  try {
    const { data, sections, homeSlug, defaultLanguage } = options

    const clonedData = _cloneDeep(data)

    if (options.debug) {
      console.log('📇 generateRoutesFromData options: ', options)
    }

    // flatten data to get all nested pages
    // This is normally only needed if you pass in your navigations file,
    // which has nested pages, to be represented in the navigation
    // if your data is on one level only, even better.
    const flattenedData = flattenNavigation({
      navigationData: clonedData,
      sections
    })

    // add language prefixes like:
    // uri: 'parent-page/nested-page' ==> uri: 'en/parent-page/nested-page'
    // for every language except the default language
    // (we have to do this because on entry level in craft we don't know the language (or the prefix))
    // but for that we need to know the default language
    const prefixedData = addLanguagePrefixes({
      data: flattenedData,
      defaultLanguage
    })

    console.log('prefixedData: ', prefixedData)

    let routes = []

    // go through each language
    Object.keys(prefixedData).map(lang => {
      // and through each section
      sections.forEach(section => {
        const entryURIs = prefixedData[lang][section].map(entry => entry.uri)
        routes.push(...entryURIs)
      })
    })

    // Kick out all the pages ending with the home slug
    // this will delete all homes for each language
    // it also means we can't have nested pages in home
    // Sadly this step is necessary since we can not redirect() with our middleware during generate
    routes = routes
      .filter(r => {
        // Removing 'home' or '/home'
        return r !== homeSlug && r !== `/${homeSlug}`
      })
      // remove slashes and truncate 'de/home' to 'de' etc.
      .map(r => {
        return verifyLeadingSlash(stripTrailingHomeSlug(removeTrailingSlash(r)))
      })

    if (options.debug) {
      console.log('📇 generateRoutesFromData routes', routes)
    }
    return routes
  } catch (e) {
    console.log(
      'generateRoutesFromData: 🗃 ❌ generateRoutesFromData() failed: ',
      e
    )
  }
}

export default generateRoutesFromData
