query Navigations($section: String) {
  entries(section: [$section], level: 1) {
    slug
    uri
    title
    children {
      slug
      uri
      title
      children {
        slug
        uri
        title
      }
    }
  }
}
