#import "./fragments/flexibleContent.gql"

query ($slug: String!) {
  entries(section: [pages], slug: $slug) {
    slug
    title
    ... on PageFlexContent {
      id
      title
      slug
      flexibleContent {
        ...text
        ...image
        ...teaser
      }
    }
  }
}
