#import "./fragments/seomatic.gql"

query Page($slug: String!) {
  entries(section: [pages], slug: $slug) {
    slug
    title
    ...SeoMaticFragment
    ...on Pages {
      richtext {
        totalPages
        content
      }
    }
  }
}
