query Seomatic($slug: String!) {
  seomatic(uri: $slug, asArray: true) {
    metaTitleContainer
    metaTagContainer
    metaLinkContainer
    metaJsonLdContainer
  }

  entries(section: [pages], slug: $slug) {
    ...on Pages {
      ogImage {
        url: url(transform: ogImage)
        title
      }
    }
  }
}
